### ISSUE TITLE
Any plans that this project is gonna get updated or a new project?

### ISSUE THREAD

**Issue by icodelifee** [infobip/infobip-rtc-flutter#1]

**Comment by adnanel** [comment]
Hi!

The Flutter SDK is a wrapper around the deprecated WebRTC 1.x SDK, and we currently don't offer a replacement.

Right now, you would need to wrap the native SDKs yourself.

**Comment by icodelifee** [comment]
Hey, I have updated the plugin to support the latest version of the ios library, android is work in progress. Is it okay i publish it in pub.dev and maintain it?

**Comment by icodelifee** [comment]
https://github.com/icodelifee/infobip_voice 
This is the repository, i have marked it as unofficial

**Comment by adnanel** [comment]
Hi,

As long as you mark it as unofficial I believe you should be fine publishing your lib. Good luck with your implementation.
